import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/context/ThemeContext";
import { Sidebar } from "@/components/ui/sidebar";
import ClientProviders from "@/providers/ClientProviders";
import { Headbar } from "@/components/ui/headbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "InvoiceHub",
  description: "Generated by invoiceHub",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ThemeProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased flex h-screen`}
        >
          <Sidebar />
          <div className="flex flex-col flex-1">
            <Headbar />

            <main className="flex-1 overflow-auto ">
              {" "}
              <ClientProviders>{children}</ClientProviders>{" "}
            </main>
          </div>
        </body>
      </html>
    </ThemeProvider>
  );
}
